// Generated by Copilot

using StoreLab.RetroStore.Enums;

namespace StoreLab.RetroStore;

public class ConsoleStateResult<T>
{
    public ConsoleState State { get; set; }
    public T? Argument { get; set; }

    public ConsoleStateResult(ConsoleState state, T? argument = default)
    {
        State = state;
        Argument = argument;
    }
}